In [2]:
### Using ANN to claculate 90 day breach

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
import numpy as np
import pandas as pd

/home/tommy/mypy/mypy/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [4]:
# dataset = np.loadtxt("breach-prediction-dataset-no-nulls_num.csv", delimiter=",",filling_values=-1)

In [5]:
from numpy import genfromtxt
dataset = genfromtxt("breach-prediction-dataset-no-nulls_MW.csv", delimiter=",", filling_values=-1)

In [6]:
dataset

array([[ 10.,  13.,   1., ..., 498.,  39.,   1.],
       [ 10.,  13.,   1., ..., 173.,  22.,   1.],
       [ 10.,  13.,   1., ..., 530.,  71.,   1.],
       ...,
       [  7.,   5.,   4., ..., 227.,   5.,   1.],
       [  7.,   6.,   4., ..., 227.,   4.,   1.],
       [  7.,   9.,   4., ..., 227.,   1.,   1.]])

In [7]:
X = dataset[:,0:43]

In [8]:
X

array([[1.0000000e+01, 1.3000000e+01, 1.0000000e+00, ..., 1.5112224e+09,
        4.9800000e+02, 3.9000000e+01],
       [1.0000000e+01, 1.3000000e+01, 1.0000000e+00, ..., 1.5097536e+09,
        1.7300000e+02, 2.2000000e+01],
       [1.0000000e+01, 1.3000000e+01, 1.0000000e+00, ..., 1.5139872e+09,
        5.3000000e+02, 7.1000000e+01],
       ...,
       [7.0000000e+00, 5.0000000e+00, 4.0000000e+00, ..., 1.5311808e+09,
        2.2700000e+02, 5.0000000e+00],
       [7.0000000e+00, 6.0000000e+00, 4.0000000e+00, ..., 1.5311808e+09,
        2.2700000e+02, 4.0000000e+00],
       [7.0000000e+00, 9.0000000e+00, 4.0000000e+00, ..., 1.5311808e+09,
        2.2700000e+02, 1.0000000e+00]])

In [9]:
# last variable in the dataset is the dependent variable we're trying to predict
Y = dataset[:,43]

In [10]:
Y

array([1., 1., 1., ..., 1., 1., 1.])

In [11]:
model = Sequential()
model.add(Dense(65, input_dim=43, activation='relu'))
model.add(Dense(43, activation='relu'))
model.add(Dense(21, activation='relu'))
model.add(Dense(9, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [12]:
# Compile model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

# sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

#model.compile( loss = "binary_crossentropy", optimizer = sgd, metrics=['accuracy'])

In [13]:
# Fit the model
model.fit(X, Y, epochs=300, batch_size=50)

Epoch 1/300
4343/4343 [==============================] - 0s 75us/step - loss: 6.4056 - acc: 0.5982
Epoch 2/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 3/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 4/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 5/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 6/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 7/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 8/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 9/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 10/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 11/

4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 84/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 85/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 86/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 87/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 88/300
4343/4343 [==============================] - 0s 35us/step - loss: 6.4056 - acc: 0.5982
Epoch 89/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 90/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 91/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 92/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 93/300


4343/4343 [==============================] - 0s 31us/step - loss: 6.4056 - acc: 0.5982
Epoch 165/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 166/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 167/300
4343/4343 [==============================] - 0s 30us/step - loss: 6.4056 - acc: 0.5982
Epoch 168/300
4343/4343 [==============================] - 0s 30us/step - loss: 6.4056 - acc: 0.5982
Epoch 169/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 170/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 171/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 172/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoch 173/300
4343/4343 [==============================] - 0s 38us/step - loss: 6.4056 - acc: 0.5982
Epoc

4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 246/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 247/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 248/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 249/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 250/300
4343/4343 [==============================] - 0s 34us/step - loss: 6.4056 - acc: 0.5982
Epoch 251/300
4343/4343 [==============================] - 0s 35us/step - loss: 6.4056 - acc: 0.5982
Epoch 252/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 253/300
4343/4343 [==============================] - 0s 33us/step - loss: 6.4056 - acc: 0.5982
Epoch 254/300
4343/4343 [==============================] - 0s 32us/step - loss: 6.4056 - acc: 0.5982
Epoc

In [14]:
# evaluate the model
scores = model.evaluate(X, Y)
print("\n%s: %.2f%%" % (model.metrics_names[1], scores[1]*100))

4343/4343 [==============================] - 0s 30us/step

acc: 59.82%


In [15]:
# calculate predictions
predictions = model.predict(X)

# round predictions
rounded = [round(x[0]) for x in predictions]
print(rounded)

[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0,

In [16]:
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [17]:
! type model.json

/bin/sh: line 0: type: model.json: not found


In [18]:
from keras.models import model_from_yaml

In [19]:
# serialize model to YAML
model_yaml = model.to_yaml()

with open("model.yaml", "w") as yaml_file:
    yaml_file.write(model_yaml)

# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [20]:
! type model.yaml

/bin/sh: line 0: type: model.yaml: not found


In [21]:
# Load from JSON
from keras.models import model_from_json
import numpy
import os

# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)

# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
 
# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

Loaded model from disk
acc: 59.82%


In [22]:
# load YAML and create model
yaml_file = open('model.yaml', 'r')
loaded_model_yaml = yaml_file.read()
yaml_file.close()
loaded_model = model_from_yaml(loaded_model_yaml)

# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")
 
# evaluate loaded model on test data
loaded_model.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])
score = loaded_model.evaluate(X, Y, verbose=0)
print("%s: %.2f%%" % (loaded_model.metrics_names[1], score[1]*100))

Loaded model from disk
acc: 59.82%
